로그인 페이지 개발
Team-Cavascript/About-view pull request #25
Opened 2021-08-21 13:11 UTC by yunseong76039287

로그인 페이지를 adobe xd 디자인을 보고 레이아웃만 개발해 놓았습니다.
반응형으로 페이지 크기가 바뀔 때 마다 입력창과 로그인 버튼크기가 조절되게 만들었습니다.
아직 많이 부족해 많은 피드백이 필요합니다! 감사합니다.

2021-08-22 12:42 UTC, GiPyoo requested changes
- margin 지양
- left, top 등 위치를 지정하는 css 지양
- 되도록 px을 지양(단 플렉스 방향에 따른 height나 width는 허용)
위와 같은 사항들을 고려하며 짜면 좋을 것 같습니다.

2021-08-22 13:09 UTC, ummaeha requested changes

2021-08-22 13:09 UTC, ummaeha commented on about-view/src/App.js
> +import LoginPage from "./Login/LoginPage";
PR날리기전에 ESlint를 한 번 돌리면 import 순서가 안맞는 부분은 빨간줄이 생긴다고합니다!

2021-08-22 13:09 UTC, ummaeha commented on about-view/src/App.js
> +      {/* <header className="App-header"></header> */}
불필요한 주석들은 지우는 것이 깔끔합니다!

2021-08-22 13:09 UTC, ummaeha commented on about-view/src/Login/LoginPage.css
> +  appearance: none;
css apperance라는 속성을 첨봤네용 ㅇ0ㅇ

2021-08-23 03:35 UTC, yunseong76039287 commented on about-view/src/Login/LoginPage.css
> +  appearance: none;
기본 버튼의 css를 none으로 바꿔준다고 하더라구요!

2021-08-28 11:36 UTC, ummaeha commented
아 그리구 피알날릴떄 이미지 캡쳐해서 넣어주시면 리뷰에 도움이 될 것 같습니다 :)

2021-08-28 12:10 UTC, ummaeha approved these changes
고생하셨습니다~

2021-08-28 12:12 UTC, yunseong76039287 commented
> 고생하셨습니다~

피드백 감사합니다 :D

2021-08-28 12:12 UTC, merged